export const gridData = {
  code: 100,
  success: true,
  data: [
    {
      id: '0',
      title: '成都XX集团有限公司',
      category: '一级公司',
      skin: '#F54640',
      targetNode: [
        { target: '1', label: '参股10%' },
        { target: '2', label: '全资100%' },
        { target: '3', label: '全资100%' },
        { target: '4', label: '全资100%' },
        { target: '5', label: '控股50%' },
        { target: '7', label: '参股30%' },
        { target: '8', label: '参股20%' },
        { target: '9', label: '控股10%' },
        { target: '11', label: '全资100%' },
      ],
    },
    {
      id: '1',
      category: '二级公司',
      skin: '#FFA219',
      title: '成都XX投资有限公司',
      targetNode: [{ target: '2', label: '全资100%' }],
    },
    {
      id: '2',
      category: '二级公司',
      skin: '#FFA219',
      title: '成都XX有限公司',
      targetNode: [{ target: '3', label: '控股30%' }],
    },
    {
      id: '3',
      category: '三级公司',
      skin: '#49C248',
      title: '成都XX公司',
      targetNode: [
        { target: '10', label: '控股30%' },
        { target: '12', label: '参股30%' },
      ],
    },
    {
      id: '4',
      category: '三级公司',
      skin: '#49C248',
      title: '成都XXXXX公司',
    },
    {
      id: '5',
      category: '二级公司',
      skin: '#FFA219',
      title: '成都XXXXX有限公司',
      targetNode: [{ target: '6', label: '全资100%' }],
    },
    {
      id: '6',
      category: '三级公司',
      skin: '#49C248',
      title: '成都XXXXX有限公司',
    },
    {
      id: '7',
      category: '四级公司',
      skin: '#1D76FE',
      title: '成都XXXXX有限公司',
    },
    {
      id: '8',
      category: '五级公司',
      skin: '#6F40F5',
      title: '成都XXXXX有限公司',
    },
    {
      id: '9',
      category: '四级公司',
      skin: '#1D76FE',
      title: '成都XXXXX投资有限公司',
    },
    {
      id: '10',
      category: '五级公司',
      skin: '#6F40F5',
      title: '成都XXXXX投资有限公司',
    },
    {
      id: '11',
      category: '六级公司',
      skin: '#909399',
      title: '成都XXXXX投资有限公司',
    },
    {
      id: '12',
      category: '六级公司',
      skin: '#909399',
      title: '成都XXXXX投资有限公司',
    },
  ],
};
