name: Deploy Dumi Docs

on:
  push:
    branches: [ "master", "feature/v1.0.0" ]
  workflow_dispatch:
    inputs:
      reason:
        description: "Manual trigger reason"
        required: false
        default: "manual"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && contains(github.event.head_commit.message, 'release'))
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          # 暂时移除缓存，因为此时 pnpm 还未准备

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm via Corepack
        run: corepack prepare pnpm@latest --activate

      - name: Setup pnpm cache
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'  # 现在设置缓存，此时 pnpm 已可用

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Update Changelog
        run: pnpm run changelog

      - name: Commit and Push Changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add packages/doc/docs/versions/changelog.md
          
          if ! git diff --staged --quiet; then
            git commit -m "chore: update changelog [skip ci]"
            git pull --rebase origin ${GITHUB_REF#refs/heads/}
            git push
            echo "Changelog updated and pushed."
          else
            echo "No changes in changelog to commit."
          fi

      - name: Build Project
        run: pnpm --filter "@plugin-flow-engine/doc" build

      - name: Create CNAME file
        run: echo "flow.chloehe.cn" > packages/doc/docs-dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/doc/docs-dist
          keep_files: false
          force_orphan: true
          commit_message: "deploy: update documentation ${{ github.sha }}"